<a href="https://colab.research.google.com/github/panditamey1/yt_ml/blob/main/neural_net_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Simple neural net


In [1]:
inputs = [0.4,0.6,0.8,1.2]

weights = [[0.3,0.5,0.7,-0.2],
           [-0.9,0.34,0.23,-0.1],
           [0.43,0.228,0.343,0.66]]

biases = [0.4,0.6,0.2]



In [2]:
layer_output = []

for neuron_weight, bias in zip(weights, biases):
  neuron_output = 0
  for input, weight in zip(inputs, neuron_weight):
    neuron_output += input * weight 
  neuron_output += bias
  layer_output.append(neuron_output)

In [3]:
layer_output

[1.1400000000000001, 0.508, 1.5752]

## Vectorize


In [4]:
import numpy as np


face well-known error

In [5]:
output = np.dot(inputs, weights) +  biases

ValueError: ignored

In [6]:
output = np.dot( weights, inputs) +  biases

In [7]:
output

array([1.14  , 0.508 , 1.5752])

Batch


create new input

In [9]:
inputs = [[0.4,0.6,0.8,1.2],
          [0.2,0.1,0.4,1.9],
          [0.12,0.9,1.8,2.2]]

weights = [[0.3,0.5,0.7,-0.2],
           [-0.9,0.34,0.23,-0.1],
           [0.43,0.228,0.343,0.66]]

biases = [0.4,0.6,0.2]

In [11]:
inputs = np.array(inputs)
weights = np.array(weights)

In [12]:
inputs.shape

(3, 4)

In [13]:
weights.shape

(3, 4)

Look at different dimension

In [15]:
outputs = np.dot(inputs, weights.T) + biases

In [16]:
outputs

array([[1.14  , 0.508 , 1.5752],
       [0.41  , 0.356 , 1.7   ],
       [1.706 , 0.992 , 2.5262]])

In [19]:
outputs.shape

(3, 3)

## add another layer

In [20]:
weights2 = [[0.1,0.4,0.9],
           [-0.3,0.55,0.26],
           [0.23,0.9,0.876]]

biases2 = [0.1,0.8,0.4]

In [21]:
layer2_outputs = np.dot(outputs, np.array(weights2).T) + biases2

In [22]:
layer2_outputs

array([[1.83488  , 1.146952 , 2.4992752],
       [1.8134   , 1.3148   , 2.3039   ],
       [2.94098  , 1.490612 , 3.8981312]])

## Make a object

In [24]:
class Layer_Dense:
  def __init__(self):
    pass
  def forward(self):
    pass

In [33]:
class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1,n_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

In [39]:
layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

In [35]:
X = np.array(inputs)

In [36]:
X.shape

(3, 4)

In [37]:
layer1.forward(X)

In [38]:
layer1.output

array([[ 0.12218471, -0.0392895 , -0.21178052,  0.02848441,  0.071278  ],
       [ 0.29866358,  0.05519039, -0.19971919, -0.06131904,  0.09888654],
       [ 0.24881626, -0.09094588, -0.29419477, -0.01962595,  0.09917357]])

In [42]:
layer2.forward(layer1.output)

In [43]:
layer2.output

array([[0.05109919, 0.0045299 ],
       [0.06627417, 0.03479291],
       [0.08462919, 0.01038968]])